//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class Service5Entities : DbContext
    {

        private static Service5Entities _context;

        public static Service5Entities GetContext()
        {
            if (_context == null)
            {
                _context = new Service5Entities();
            }

            return _context;
        }

        public Service5Entities()
            : base("name=Service5Entities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Devices> Devices { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Role_> Role_ { get; set; }
        public virtual DbSet<Times1> Times1 { get; set; }
        public virtual DbSet<Times2> Times2 { get; set; }
        public virtual DbSet<Type_of_repair> Type_of_repair { get; set; }
        public virtual DbSet<Warranty> Warranty { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
